---
services:
  - docker

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install yamllint -qq

script:
  - yamllint -c .lint.yml docker-compose.yml
  - cp example.env .env
  - docker-compose config
